version: "3.8"

services:
  chess_tournament:
    build:
      context: .
      dockerfile: Dockerfile.tournament  # Explicitly specify the Dockerfile
    image: chess_tournament  # Name of the built image
    container_name: chess_tournament_container
    runtime: nvidia  # Ensures GPU access
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all 
              capabilities: [gpu]
    volumes:
      - ./models:/app/models
      - ./figures:/app/figures
      - ./games:/app/games
    environment:
      - NVIDIA_VISIBLE_DEVICES=all 
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
      - XLA_FLAGS=--xla_gpu_cuda_data_dir=/usr/lib/x86_64-linux-gnu
      - TF_CPP_MIN_LOG_LEVEL=2 
      - TF_GPU_ALLOCATOR=cuda_malloc_async  
      - N_PLAYERS=10
      - N_GAMES=10
      - TEMP=0.01
      - WORKERS=4
    command: ["python", "/app/script.py"] 
    working_dir: /app